# Generated by Django 4.2 on 2023-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=20, null=True)),
                ('UserEmail', models.EmailField(blank=True, max_length=200, null=True)),
                ('UserContact', models.IntegerField(blank=True, null=True)),
                ('UserPassword', models.CharField(blank=True, max_length=20, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='UserImages')),
            ],
        ),
    ]
