# Generated by Django 4.2 on 2023-07-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_cartdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Mobile',
        ),
    ]
