# Generated by Django 4.2 on 2023-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_remove_cartdb_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddressDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=20, null=True)),
                ('BillingFirstName', models.CharField(blank=True, max_length=20, null=True)),
                ('BillingLastName', models.CharField(blank=True, max_length=20, null=True)),
                ('BillingCompanyName', models.CharField(blank=True, max_length=20, null=True)),
                ('BillingMail', models.EmailField(blank=True, max_length=100, null=True)),
                ('BillingAddress1', models.CharField(blank=True, max_length=100, null=True)),
                ('BillingAddress2', models.CharField(blank=True, max_length=100, null=True)),
                ('BillingCity', models.CharField(blank=True, max_length=100, null=True)),
                ('BillingState', models.CharField(blank=True, max_length=100, null=True)),
                ('BillingContact', models.IntegerField(blank=True, null=True)),
                ('BillingPincode', models.IntegerField(blank=True, null=True)),
                ('BillingComments', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
